version: "3.6"

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.9

x-flask-volumes: &flask_volumes
  volumes:
    - ./flask_app/:/app
    - node-modules:/app/node_modules
x-notebook-volumes: &notebook_volumes
  volumes:
    - ./ui/notebooks:/nb

services:
  spark-notebook:
    build:
      context: ./ui
      dockerfile: Dockerfile
      target: notebook
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "8888:8888"
    <<: *notebook_volumes

  flask-dev:
    build:
      context: ./flask_app
      target: development
      args:
        <<: *build_args
    image: "flask_app-development"
    ports:
      - "5000:5000"
      - "2992:2992"
    <<: *flask_volumes

  flask-prod:
    build:
      context: ./flask_app
      target: production
      args:
        <<: *build_args
    image: "flask_app-production"
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    <<: *flask_volumes

  manage:
    build:
      context: ./flask_app
      target: development
      args:
        <<: *build_args
    entrypoint: flask
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "flask_app-manage"
    stdin_open: true
    tty: true
    <<: *flask_volumes

volumes:
  node-modules:
