version: "3.6"

services:

  backend:
    ports:
      - "8888:8888"
    volumes:
      - ./fastapi_app/backend/app:/app
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    build:
      context: ./fastapi_app/backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    # command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
    command: /bin/sh -c "/app/start-reload.sh"

  celeryworker:
    volumes:
      - ./fastapi_app/backend/app:/app
    environment:
      - RUN=celery worker -A app.worker -l info -Q main-queue -c 1
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    build:
      context: ./fastapi_app/backend
      dockerfile: celeryworker.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}

  pyspark-notebook:
    ports:
      - "8008:8008"

  neo:
      # map the ports so we can check the db server is up
      ports: 
        - 7474:7474
        - 7687:7687
