version: "3.6"

x-notebook-volumes: &notebook_volumes
  volumes:
    - ./ui/notebooks:/nb

services:
  queue:
    image: rabbitmq:3-management
    # Using the below image instead is required to enable the "Broker" tab in the flower UI:
    # image: rabbitmq:3-management
    #
    # You also have to change the flower command
  
  flower:
    image: mher/flower
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
      - default
    depends_on:
      - celeryworker
      - queue
    env_file:
      - .env
    command: ["celery", "--broker=amqp://guest:guest@queue:5672//", "flower", "--broker_api=http://guest:guest@queue:15672/api//", "--inspect_timeout=10000"]
    # command: ["celery", "flower", "--broker_api=http://guest:guest@queue:15672/api/", "--port=5555"] 
      # - "--broker_api=http://guest:guest@queue:15672/api//"
      # For the "Broker" tab to work in the flower UI, uncomment the following command argument,
      # and change the queue service's image as well
      # - "--broker_api=http://guest:guest@queue:15672/api//"
    ports:
      - "5555:5555"
  
  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    env_file:
      - .env
    depends_on:
      - neo
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
    build:
      context: ./fastapi_app/backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
  
  celeryworker:
    image: '${DOCKER_IMAGE_CELERYWORKER?Variable not set}:${TAG-latest}'
    depends_on:
      - queue
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
    build:
      context: ./fastapi_app/backend
      dockerfile: celeryworker.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

  pyspark-notebook:
    build:
      context: ./ui
      dockerfile: Dockerfile
      target: notebook
    environment:
      - JUPYTER_ENABLE_LAB="yes"     
    <<: *notebook_volumes

  neo:
    # The image to use
    image: neo4j:latest
    # mounting a named volume to the container to track db data
    volumes:
        - neo4j_data:/data/
    env_file:
        - .env

volumes:
  app-db-data:
  neo4j_data:
