default_context:
  project_name: 'fastapi_app'
  project_slug: 'fastapi_app'
  domain_main: 'fastapi_app.com'
  domain_staging: 'stag.fastapi_app.com'
  docker_swarm_stack_name_main: 'fastapi_app-com'
  docker_swarm_stack_name_staging: 'stag-fastapi_app-com'
  secret_key: 'changethis'
  first_superuser: 'admin@fastapi_app.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fastapi_app.com", "https://stag.fastapi_app.com", "https://fastapi_app.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  traefik_constraint_tag: 'fastapi_app.com'
  traefik_constraint_tag_staging: 'stag.fastapi_app.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  _template: ./
